user:
  name: shanewilkins
  email: null
paths:
  roadmap_dir: .roadmap
  logs_dir: .roadmap/logs
  db_dir: .roadmap/db
github:
  owner: shanewilkins
  repo: roadmap
  enabled: true
  sync_enabled: true
  sync_backend: github
  webhook_secret: null
  sync_settings:
    bidirectional: true
    auto_close: true
    sync_labels: true
    sync_milestones: true
display:
  default_milestone: null
  table_width: 100
